### ISSUE TITLE
Problem in OMNIKEY 5023 CL

### ISSUE THREAD

**Issue by Bekakk** [Qingbao/SmartID#1]
Hello
Thanks your great repository.I have one problem ,I try to explain about my problem and please share your experience and help me 
I have OMNIKEY 5023 CL device .I used  inteliJ ID.Successfully imported your project and when i run Reader.java file  i Reaceved Swing view and  when i put my  own ID card-nothing happened.
As you said you tested your repository in HID OMNIKEY 5321 and i use OMNIKEY 5023.Is a problem ,because i use different device version ?
Thanks

**Comment by Qingbao** [comment]
Hi,
Have you uploaded the applet to the card?

**Comment by Qingbao** [comment]
Or try to test your reader with some code like below see if it works?
```java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javacardreaderexample;

import java.util.List;
import javax.smartcardio.Card;
import javax.smartcardio.CardChannel;
import javax.smartcardio.CardException;
import javax.smartcardio.CardTerminal;
import javax.smartcardio.TerminalFactory;

/**
 *
 * @author qingbao
 */
public class Main {

	/**
	 * @param args the command line arguments
	 */
	public static void main(String[] args) throws CardException {
		// show the list of available terminals
		TerminalFactory factory = TerminalFactory.getDefault();
		List<CardTerminal> terminals = factory.terminals().list();
		System.out.println("Terminals: " + terminals);
		// get the first terminal
		CardTerminal terminal = terminals.get(1);
		// establish a connection with the card
		Card card = terminal.connect("*");
		System.out.println("card: " + card);
		CardChannel channel = card.getBasicChannel();
		//ResponseAPDU r = channel.transmit(new CommandAPDU(c1));
		//System.out.println("response: " + toString(r.getBytes()));
		// disconnect
		card.disconnect(false);
	}

}
```

**Comment by Bekakk** [comment]
Your code throwing exceptions.I changed it and i can get Terminal name : [PC/SC terminal HID Global OMNIKEY 5023 Smart Card Reader 0]
card: PC/SC card in HID Global OMNIKEY 5023 Smart Card Reader 0, protocol T=1, state OK

Here is a source




`public class Main {
    public static void main(String[] args) throws CardException {
        TerminalFactory factory = TerminalFactory.getDefault();
        List<CardTerminal> terminals = factory.terminals().list();
        System.out.println("Terminals: " + terminals);
        for (int i = 0; i < terminals.size(); i++) {
            CardTerminal terminal = terminals.get(i);
            Card card = terminal.connect("*");
            System.out.println("card: " + card);
            CardChannel channel = card.getBasicChannel();
            card.disconnect(false);
        }
    }

}`

**Comment by Qingbao** [comment]
Yes, your reader seems to work, have you uploaded the applet to your card?

**Comment by Bekakk** [comment]
No.
Now i try to read all Information from Card(firstName,Lastname and etc) is it a possible to read all data from Card with your Library ?

**Comment by Qingbao** [comment]
Well...it's actually for reading and writing for this project
https://github.com/Qingbao/JavaCardAppletAndUploadScript and cannot be read
without this applet.

2017-08-01 8:15 GMT+02:00 Beka Kukhalashvili <notifications@github.com>:

**Comment by Bekakk** [comment]
Did you understand my problem?
Is it a possible to solve my problem with  your JavaCardAppletAndUploadScript Library?
Thanks

**Comment by Qingbao** [comment]
From my understanding is that you wanted to read your card with this project as a lib, but in fact this project is dedicated for reading and writing with https://github.com/Qingbao/JavaCardAppletAndUploadScript, 
So unfortunately the answer is you cannot. However if you wanted to build a customized application for you card and reader, you can refer with http://scuba.sourceforge.net/ which is more general lib than this one, and I also use it as a dependency lib in this project.

**Comment by Qingbao** [comment]
Issue closed since no more questions.
