### ISSUE TITLE
I cant run reader on windows

### ISSUE THREAD

**Issue by ghost** [Qingbao/SmartID#4]
Im able to run the writer.bat and the app shows up but when I want to run the reader.bat nothing happens, only cmd opens

**Comment by Qingbao** [comment]
Try to run from the source code or  java -jar "/dist/SmartID.jar"

**Comment by tayyib195** [comment]
I only get a cmd window saying 'Inserted card" or "Removed card" I dont see anything else, how does it read?

**Comment by Qingbao** [comment]
You card doesn't have the applet to read from, you need to write it first.

**Comment by tayyib195** [comment]
I am trying to read a real epassport..

**Comment by tayyib195** [comment]
I just want to have a simple program which I can use to read epassports..I just want to verify that they're real

**Comment by Qingbao** [comment]
You might need to modify the source code in order to do that as a newly issued epassport might use different encryption algorithm, unfortunately this repo is relatively old and not actively maintained.

**Comment by tayyib195** [comment]
Sir could you make an updated version for the jmrtd windows application? https://sourceforge.net/projects/jmrtd/files/passporthostapi/0.4.9/

**Comment by Qingbao** [comment]
BAC=passport No. + DoB + DoE

**Comment by tayyib195** [comment]
Yes I know thats BAC, but there is nowhere to type in bac, I only get a cmd window.. How can I read the passport if theres nowhere to
type in bac?

**Comment by Qingbao** [comment]
Why not just use jmrtd directly?

**Comment by tayyib195** [comment]
JMRTD 0.4.9 installer you mean? That almost works for me, it starts reading and then it stops reading after a second, I can see the passport info for a millisecond and then it disappears, apdu stops too

**Comment by Qingbao** [comment]
what reader are you using?

**Comment by tayyib195** [comment]
![Uploading image.jpg…]()

**Comment by tayyib195** [comment]
![image](https://github.com/Qingbao/SmartID/assets/36987761/ae2d86c5-3537-40cf-a02a-d5f75008d7ef)
This is all I get from your app

**Comment by tayyib195** [comment]
![Uploading image.jpg…]()
this reader

**Comment by tayyib195** [comment]
![image](https://github.com/Qingbao/SmartID/assets/36987761/62d35d8c-aa4d-485e-81ab-37b0bfd5bb36)
This reader

**Comment by Qingbao** [comment]
This app is not made for reading ePassports but a dedicated applet. You might need to use JMRTD, you can get source code and it also available on Google Play Store

**Comment by tayyib195** [comment]
https://sourceforge.net/projects/jmrtd/files/passporthostapi/0.4.9/

Sir here is the latest windows installer for jmrtd which was from 2013, he didnt make any more installers but kept updating the database of jmrtd,
you would do a lot of people a big favor if you could update the installer for the newest database
