### ISSUE TITLE
idcard and smartidcard

### ISSUE THREAD

**Issue by vrtkarim** [Qingbao/SmartID#7]
when adding the card i cant write on it and only shows that idcard inserted and not smartcard inserted.

**Comment by Qingbao** [comment]
What kind of card are you using?

**Comment by vrtkarim** [comment]
> What kind of card are you using?

what type should i use? can you check your gmail box

**Comment by Qingbao** [comment]
You should use:
HID OMNIKEY 5321 card reader, and SmartCafe expert 3.2 smart card with JavaCard 2.2.1
